import PDFDocument from 'pdfkit';
import { v2 as cloudinary } from 'cloudinary';
import { Transaction, User } from '@prisma/client';
import { PassThrough } from 'stream';

export class PdfGeneratorService {
  /**
   * Generates a PDF receipt for a list of transactions and uploads it to Cloudinary
   */
  static async generateTransactionReceipt(transactions: Transaction[], user: User): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        
        // Create a pass-through stream to capture the PDF data
        const stream = new PassThrough();
        
        doc.pipe(stream);
        
        // Collect buffers
        stream.on('data', (chunk) => buffers.push(chunk));
        stream.on('end', async () => {
          try {
            const pdfBuffer = Buffer.concat(buffers);
            const base64Pdf = pdfBuffer.toString('base64');
            const dataUri = `data:application/pdf;base64,${base64Pdf}`;
            
            // Upload to Cloudinary
            const uploadResult = await cloudinary.uploader.upload(dataUri, {
              resource_type: 'auto', // Use 'auto' to let Cloudinary detect PDF as image/document for better delivery
              folder: 'ghana-poc-receipts',
              public_id: `receipt_${user.phoneNumber}_${Date.now()}`,
              format: 'pdf'
            });
            
            console.log('PDF Receipt uploaded:', uploadResult.secure_url);
            resolve(uploadResult.secure_url);
          } catch (err) {
            reject(err);
          }
        });

        // --- PDF Content ---
        
        // Header
        doc.fontSize(20).text('Transaction Receipt', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Date: ${new Date().toLocaleString()}`);
        doc.text(`Customer: ${user.firstName} ${user.lastName} (${user.phoneNumber})`);
        doc.moveDown();
        
        // Divider
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
        
        // Table Header
        const startY = doc.y;
        doc.font('Helvetica-Bold');
        doc.text('Item', 50, startY);
        doc.text('Type', 200, startY);
        doc.text('Amount', 350, startY);
        doc.text('Currency', 450, startY);
        doc.font('Helvetica');
        doc.moveDown();
        
        // Transactions
        let totalAmount = 0;
        
        transactions.forEach(tx => {
          const y = doc.y;
          doc.text(tx.item || 'Unspecified', 50, y);
          doc.text(tx.type, 200, y);
          doc.text(tx.amount.toString(), 350, y);
          doc.text(tx.currency, 450, y);
          
          if (tx.type === 'INCOME' || tx.type === 'EXPENSE') {
             // Simple sum for now, though mixing income/expense in total might be confusing
             // Let's just list them.
          }
          doc.moveDown();
        });
        
        // Divider
        doc.moveDown();
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
        
        // Footer
        doc.fontSize(10).fillColor('grey').text('Generated by Ghana Tax Assistant', { align: 'center' });
        
        doc.end();
        
      } catch (error) {
        reject(error);
      }
    });
  }
  /**
   * Generates a Tax Payment Receipt (GRA Style)
   */
  static async generateTaxReceipt(transaction: Transaction, user: User): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];
        
        const stream = new PassThrough();
        doc.pipe(stream);
        
        stream.on('data', (chunk) => buffers.push(chunk));
        stream.on('end', async () => {
          try {
            const pdfBuffer = Buffer.concat(buffers);
            const base64Pdf = pdfBuffer.toString('base64');
            const dataUri = `data:application/pdf;base64,${base64Pdf}`;
            
            const uploadResult = await cloudinary.uploader.upload(dataUri, {
              resource_type: 'auto',
              folder: 'ghana-poc-receipts',
              public_id: `tax_receipt_${user.phoneNumber}_${Date.now()}`,
              format: 'pdf'
            });
            
            console.log('Tax Receipt uploaded:', uploadResult.secure_url);
            resolve(uploadResult.secure_url);
          } catch (err) {
            reject(err);
          }
        });

        // --- GRA Receipt Content ---
        
        // 1. Header with Logo (Simulated text for now)
        doc.font('Helvetica-Bold').fontSize(16).text('GHANA REVENUE AUTHORITY', { align: 'center' });
        doc.fontSize(10).text('DOMESTIC TAX REVENUE DIVISION', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(14).text('PAYMENT SLIP', { align: 'center', underline: true });
        doc.moveDown();

        // 2. PRN Box
        const prn = transaction.rawText?.replace('PRN: ', '') || 'N/A';
        
        doc.rect(50, doc.y, 500, 30).stroke();
        doc.font('Helvetica-Bold').fontSize(12).text(`Payment Reference Number (PRN): ${prn}`, 60, doc.y + 10);
        doc.moveDown(2);

        // 3. Taxpayer Details
        const startY = doc.y;
        
        doc.font('Helvetica-Bold').fontSize(10).text('Taxpayer Name:', 50, startY);
        doc.font('Helvetica').text(`${user.firstName} ${user.lastName}`, 150, startY);
        
        doc.font('Helvetica-Bold').text('TIN:', 300, startY);
        doc.font('Helvetica').text(user.tinNumber || 'N/A', 350, startY);
        doc.moveDown();

        doc.font('Helvetica-Bold').text('Tax Office:', 50);
        doc.font('Helvetica').text('STO - ADABRAKA', 150); // Hardcoded for POC
        doc.moveDown();

        doc.font('Helvetica-Bold').text('Date:', 300, doc.y - 15);
        doc.font('Helvetica').text(new Date().toLocaleDateString(), 350, doc.y - 15);
        doc.moveDown(2);

        // 4. Payment Details Table
        const tableTop = doc.y;
        doc.font('Helvetica-Bold');
        doc.text('Tax Type', 50, tableTop);
        doc.text('Period', 200, tableTop);
        doc.text('Amount (GHS)', 400, tableTop);
        
        doc.moveTo(50, tableTop + 15).lineTo(500, tableTop + 15).stroke();
        
        doc.font('Helvetica');
        const rowY = tableTop + 25;
        doc.text('Turnover Tax', 50, rowY);
        doc.text(transaction.item || 'N/A', 200, rowY);
        doc.text(Number(transaction.amount).toFixed(2), 400, rowY);
        
        doc.moveTo(50, rowY + 15).lineTo(500, rowY + 15).stroke();

        // 5. Total
        doc.font('Helvetica-Bold');
        doc.text('TOTAL PAYABLE:', 250, rowY + 30);
        doc.text(Number(transaction.amount).toFixed(2), 400, rowY + 30);
        
        doc.moveDown(4);

        // 6. Footer / Instructions
        doc.fontSize(8).fillColor('grey');
        doc.text('Instructions:', 50);
        doc.text('1. Present this slip at any designated bank to make payment.');
        doc.text('2. Payment can also be made via Mobile Money using the PRN.');
        doc.text('3. This PRN expires in 7 days.');
        
        doc.end();
        
      } catch (error) {
        reject(error);
      }
    });
  }
}
